#!/bin/bash

if [[ -a ${HOME}/.emacs ]]; then
	mv ${HOME}/.emacs ${HOME}/_emacs.bak
fi

if [[ -a ${HOME}/.emacs.d ]]; then
	mv ${HOME}/.emacs.d ${HOME}/_emacs.d.bak
fi

cp `pwd`/_emacs ${HOME}/.emacs
cp -r `pwd`/_emacs.d ${HOME}/.emacs.d

